<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->delete();

        DB::table('users')->insert([
            0 => [
                'id' => 1,
                'name' => 'admin',
                'email' => 'admin@example.com',
                'email_verified_at' => '2020-11-20 10:58:03',
                'password' => '$2y$10$X31bD/0awizBfvE/UKwo/OhCH4C.H5cgLYeEeuBo6nzOi3ad.70Zq',
                'role' => 1,
                'remember_token' => null,
                'created_at' => '2020-11-19 18:29:05',
                'updated_at' => '2020-11-20 10:58:03',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'test1',
                'email' => 'test1@example.com',
                'email_verified_at' => '2020-11-20 02:39:45',
                'password' => '$2y$10$dsb7cmqbCPQRyrzE2Fyvcu.Ah0Lu23//n34LIf.bA/EpDcfgOaBee',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 02:39:09',
                'updated_at' => '2020-11-20 02:39:45',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'test2',
                'email' => 'test2@example.com',
                'email_verified_at' => null,
                'password' => '$2y$10$YhcawWMt6.1alATdneEAD.bv37L.7FRcVTziiLlqwGqF4loMs5V42',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 02:48:34',
                'updated_at' => '2020-11-20 02:48:34',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'test3',
                'email' => 'test3@example.com',
                'email_verified_at' => '2020-11-20 02:50:04',
                'password' => '$2y$10$tAh/VK1eBgSjMdGKp78XNOiKbjirtVBRXIrJpgzV4hJWIy1cbQAPq',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 02:49:47',
                'updated_at' => '2020-11-20 02:50:04',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'test4',
                'email' => 'test4@example.com',
                'email_verified_at' => '2020-11-20 11:03:03',
                'password' => '$2y$10$nfgLnGzXutv0g74K3IgyNe3UPM9szsjCFgBteoRMLMtTphKDGQEAm',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 11:02:31',
                'updated_at' => '2020-11-20 11:03:03',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'test5',
                'email' => 'test5@example.com',
                'email_verified_at' => null,
                'password' => '$2y$10$0rtjIZvVx4mAyaXc.Cr4EuSe3bhc8xQ1w55N9QZrIfP9BryJv7a/y',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 11:15:30',
                'updated_at' => '2020-11-20 11:15:30',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'name' => 'test6',
                'email' => 'test6@example.com',
                'email_verified_at' => null,
                'password' => '$2y$10$V1lUV1cjC3oFUwJbPiczweyMXdaU2BPQ8moDaFBRSIvrzqbI0Sst6',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 11:17:03',
                'updated_at' => '2020-11-20 11:17:03',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 8,
                'name' => 'test7',
                'email' => 'test7@example.com',
                'email_verified_at' => '2020-11-20 11:20:28',
                'password' => '$2y$10$JMILRgkiXTWX9L77F0J0C.r3Kr.9C4NBnrD4QeIuGsyMx41AA7HE6',
                'role' => 0,
                'remember_token' => null,
                'created_at' => '2020-11-20 11:19:24',
                'updated_at' => '2020-11-20 11:20:28',
                'stripe_id' => null,
                'card_brand' => null,
                'card_last_four' => null,
                'trial_ends_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
